# Generated by Django 6.0.1 on 2026-01-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=30, unique=True)),
                ('visitor_name', models.CharField(max_length=30)),
                ('visitor_email', models.EmailField(max_length=30)),
                ('category', models.CharField(max_length=15)),
                ('document', models.FileField(blank=True, null=True, upload_to='static/documents')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.CharField(max_length=100)),
                ('designated_attendee', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
